### ISSUE TITLE
Add new type error to deal with Daemon RPC inconsistencies

### ISSUE THREAD

**Issue by LeoNero** [monero-ecosystem/monero-rpc-rs#58]
As written in #56 , some Daemon RPC calls return inconsistent results if there is an error.

For example, the RPC call `on_get_block_hash`, when passed an height that is invalid, returns `200 OK` with response:
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": "0000000000000000000000000000000000000000000000000000000000000000"
}
```

The code https://github.com/monero-ecosystem/monero-rpc-rs/blob/master/src/lib.rs#L277 also returns `Ok()` on this case.

Should we deal with those inconsistencies by introducing a new error type?

**Comment by TheCharlatan** [comment]
This has been annoying me as well and I am not sure how we should handle this. I agree that these should be proper errors, but I don't have a template Error type for you that we can apply to these cases. Let me know if you have a suggestion for encapsulating this nicely.

**Comment by LeoNero** [comment]
@TheCharlatan  See the PR for how this was handled.
