### ISSUE TITLE
Document user-facing usage of this library with monero-rs

### ISSUE THREAD

**Issue by h4sh3d** [monero-ecosystem/monero-rpc-rs#66]
As mentioned in https://github.com/monero-ecosystem/monero-rpc-rs/pull/62#pullrequestreview-1036782456 this library already uses `monero-rs` as a user required library, and I think it's totally fine given we are on an RPC library. It should allow querying and transforming response into native `monero-rs` types.

We have to choices:
1. we document that users should install in their dependencies `monero` and `monero-rpc`
2. we `pub extern crate monero;` so using this library already provide an access to `monero-rs` types (this is what e.g. bitcoin rpc does)

**Comment by LeoNero** [comment]
I think `2.` is a good idea. I saw that pattern in other libraries as well, such as `jsonrpc_core` exporting `futures`.

**Comment by LeoNero** [comment]
And this is automatically documented by `docs` on the `Re-exports` section :)
