### ISSUE TITLE
Confusing naming of daemons

### ISSUE THREAD

**Issue by LeoNero** [monero-ecosystem/monero-rpc-rs#69]
The `DaemonClient` makes requests to `/json_rpc`, and the `DaemonRpcClient` makes requests to `/method_here`. This is a bit confusing. Probably the names should be switched.

**Comment by h4sh3d** [comment]
Agree with this one, when adding some docs recently I got confused at first with this inversion.

**Comment by TheCharlatan** [comment]
I don't think they are inverted, but rather the `DaemonClient` should be called `DaemonJsonRpcClient` or something along those lines.

**Comment by LeoNero** [comment]
@TheCharlatan Agreed :) I can change that
